# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
  checking:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:2.7-node'
      - environment:
          POSTGRES_DB: lunch_buddy_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: minira
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: minira
      RAILS_ENV: test
      BUNDLER_VERSION: 2.1.4
    parallelism: 3
    steps:
      - checkout
      - ruby/install:
          version: '2.6.5'
      - ruby/install-deps
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rubocop-check

orbs:
  node: circleci/node@2
  ruby: circleci/ruby@2.6.5
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
